### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Aegonek**
Fixed broken link to contribution guide. Fixed a typo. OCD fix before working on serious stuff.

### CODE REVIEW

**Comment by WittleWolfie** [comment]
Please build release config & commit the docsite updates as well.

**Comment by WittleWolfie** [comment]
If there are more changes in the docsite than just your changes lmk and you can ignore. I'm trying to be stricter about not updating the docsite until a release is pushed, but there might be some changes I made since the last release in main that aren't ready for publish.

**Comment by Aegonek** [comment]
Is there a need to push a new release? Only the README was changed, and it isn't included in the release.

**Comment by Aegonek** [comment]
I think I see what you mean now, README and articles are synced, right? Abandoning this pull request for now, will redo it after patch 1.1.6 compatibility gets merged.

**Comment by WittleWolfie** [comment]
The website is generated using DocFX and the README is actually the home page for the doc website. When you build the release configuration it generates the DocFX updates.

**Pull request closed without merging**
